// Print-to-PDF helper. Uses the browser's print engine to handle Arabic
// fonts and RTL correctly (jsPDF would need custom font embedding).
export function printReportAsPDF(opts: {
  title: string;
  meta?: Record<string, string>;
  summary?: string | null;
  content?: string | null;
  lang?: "ar" | "en";
}) {
  const { title, meta = {}, summary, content, lang = "ar" } = opts;
  const dir = lang === "ar" ? "rtl" : "ltr";
  const win = window.open("", "_blank", "width=900,height=1100");
  if (!win) return;
  const escape = (s: string) =>
    s.replace(/[&<>"']/g, (c) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!,
    );
  const metaRows = Object.entries(meta)
    .map(
      ([k, v]) =>
        `<tr><th style="text-align:${lang === "ar" ? "right" : "left"};padding:6px 12px;background:#faf5e6;color:#7a5a00;font-weight:600;width:30%">${escape(
          k,
        )}</th><td style="padding:6px 12px;border-bottom:1px solid #eee">${escape(v)}</td></tr>`,
    )
    .join("");
  win.document.write(`<!doctype html>
<html lang="${lang}" dir="${dir}">
<head>
<meta charset="utf-8" />
<title>${escape(title)}</title>
<style>
  @page { size: A4; margin: 18mm; }
  body { font-family: -apple-system, "Segoe UI", "Tahoma", "Arial", sans-serif; color: #1a1a1a; line-height: 1.7; }
  h1 { color: #b08800; border-bottom: 2px solid #b08800; padding-bottom: 8px; margin-bottom: 4px; font-size: 22px; }
  .brand { color: #7a5a00; font-size: 12px; letter-spacing: 1px; text-transform: uppercase; }
  .summary { background: #fffbe8; border-${lang === "ar" ? "right" : "left"}: 4px solid #b08800; padding: 12px 16px; border-radius: 6px; margin: 16px 0; font-size: 13px; }
  table { width: 100%; border-collapse: collapse; margin: 14px 0; font-size: 13px; }
  pre { white-space: pre-wrap; word-wrap: break-word; font-family: inherit; font-size: 13px; background: #fafafa; padding: 14px; border-radius: 6px; border: 1px solid #eee; }
  footer { margin-top: 30px; text-align: center; color: #888; font-size: 11px; border-top: 1px solid #eee; padding-top: 10px; }
</style>
</head>
<body>
  <div class="brand">SAMGOLD GPR</div>
  <h1>${escape(title)}</h1>
  ${metaRows ? `<table>${metaRows}</table>` : ""}
  ${summary ? `<div class="summary">${escape(summary)}</div>` : ""}
  ${content ? `<pre>${escape(content)}</pre>` : ""}
  <footer>${lang === "ar" ? "تم إنشاء هذا التقرير بواسطة" : "Generated by"} SAMGOLD GPR — ${new Date().toLocaleString(lang)}</footer>
  <script>setTimeout(()=>{window.print();},250);</script>
</body>
</html>`);
  win.document.close();
}